import { ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, ChevronRight, CreditCard, FileClock, Home, MoreHorizontal, Plus, QrCode, ScanLine, Send, ShieldCheck, Smartphone, Sparkles, Users, Wallet, Zap } from "lucide-react";
import { Avatar, Button, DemoDisclaimer, LandmarkIcon, PageHeading, QuickAction, SectionHeading, TransactionRow, useApp, money, relativeTime } from "./shared";

export function HomePage() {
  const { data, t, navigate, unread } = useApp();
  const hour = new Date().getHours();
  const greeting = hour < 12 ? t("greetingMorning") : hour < 17 ? t("greetingAfternoon") : t("greetingEvening");
  const recent = data.transactions.slice(0, 4);
  return <div className="home-page">
    <div className="welcome-row"><div><div className="eyebrow">TUESDAY, {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long" }).toUpperCase()}</div><h1>{greeting}, <span>Ritu</span></h1><p>{t("homeTagline")}</p></div><button onClick={() => navigate("/notifications")} className="home-bell" aria-label="Open notifications"><Bell size={20} />{unread > 0 && <i>{unread}</i>}</button></div>
    <div className="home-grid"><div className="home-main-column">
      <section className="balance-card"><div className="balance-card-top"><div className="bank-label"><span className="bank-emblem"><LandmarkIcon /></span><div><b>Secure Demo Bank</b><small>•••• 4521 <span className="connected"><i /> Connected</span></small></div></div><button onClick={() => navigate("/balance")} className="balance-more" aria-label="Balance details"><MoreHorizontal size={20} /></button></div><div className="balance-label">{t("available")}</div><div className="balance-amount"><span>₹ ••••••</span><button className="check-balance-link" onClick={() => navigate("/balance/verify")}>Check Balance</button></div><div className="balance-divider" /><div className="balance-quick-actions"><button onClick={() => navigate("/balance")}><span><Plus size={18} /></span>{t("addMoney")}</button><button onClick={() => navigate("/send")}><span><ArrowUpRight size={18} /></span>{t("send")}</button><button onClick={() => navigate("/request")}><span><ArrowDownLeft size={18} /></span>{t("request")}</button><button onClick={() => navigate("/scan")}><span><ScanLine size={18} /></span>{t("scan")}</button></div></section>
      <section className="quick-section"><SectionHeading title={t("quickActions")} /><div className="quick-grid"><QuickAction icon={<QrCode />} label={t("scanQR")} color="mint" onClick={() => navigate("/scan")} /><QuickAction icon={<Send />} label={t("send")} color="blue" onClick={() => navigate("/send")} /><QuickAction icon={<ArrowDownLeft />} label={t("request")} color="purple" onClick={() => navigate("/request")} /><QuickAction icon={<Zap />} label={t("payBills")} color="amber" onClick={() => { const r = { id: "electricity", name: "Electricity", upiId: "electricity@billpay", phone: "", trusted: true, riskLevel: "trusted" as const, lastTransaction: "Bill payment" }; navigate("/amount", { state: { recipient: r } }); }} /><QuickAction icon={<Smartphone />} label={t("recharge")} color="rose" onClick={() => { const r = { id: "recharge", name: "Mobile Recharge", upiId: "recharge@securepay", phone: "", trusted: true, riskLevel: "trusted" as const, lastTransaction: "Recharge" }; navigate("/amount", { state: { recipient: r } }); }} /><QuickAction icon={<LandmarkIcon />} label={t("bankTransfer")} color="green" onClick={() => navigate("/send")} /><QuickAction icon={<Users />} label={t("contacts")} color="lavender" onClick={() => navigate("/send")} /></div></section>
      <section className="recent-section"><SectionHeading title={t("recent")} action={t("seeAll")} onClick={() => navigate("/history")} /><div className="transaction-list">{recent.map(tx => <TransactionRow key={tx.id} tx={tx} onClick={() => navigate(`/transaction/${tx.id}`)} />)}</div></section>
    </div><aside className="home-side-column"><section className="security-summary"><div className="security-summary-head"><span className="security-icon"><ShieldCheck size={20} /></span><span className="status-pill"><i /> {t("active")}</span></div><h3>{t("protected")}</h3><p>Adaptive security is watching over every payment.</p><div className="score-line"><div><small>SECURITY SCORE</small><strong>94<span>/100</span></strong></div><div className="score-ring"><span>94</span></div></div><button onClick={() => navigate("/security")}>{t("viewSecurity")}<ArrowRight size={15} /></button></section>
      <section className="side-events"><SectionHeading title={t("securityActivity")} action="View all" onClick={() => navigate("/security/activity")} />{data.events.slice(0, 3).map(ev => <div className="mini-event" key={ev.id}><span><ShieldCheck size={15} /></span><div><b>{ev.type}</b><small>{relativeTime(ev.timestamp)}</small></div></div>)}</section>
      <button className="demo-promo" onClick={() => navigate("/settings")}><span><Sparkles size={18} /></span><div><b>{t("exploreScenarios")}</b><small>Test all four adaptive risk levels</small></div><ChevronRight size={17} /></button></aside></div>
    <DemoDisclaimer />
  </div>;
}
